# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c6f2c4b7f7ca6b9c44a50b85727b130a7e087e1151ba3a37357f16657523c36d61ba7b04370c46708ac74e7eef6136aa72bb4ec152e75427e28b693e1c78817

test:
  secret_key_base: 6354373f307df803e7b5243a06c5b4ab135eb60cc31e870c65c2949a4baf4d97550e4750f002aec4031bec94c923f2e4e77603512d6bea7f9472fcad57547d19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
